config/routes.rb
SummitDoodles::Application.routes.draw do
  
  resources :email_priorities
  resources :weight_reports
  
  match '/reports/expense', :to => 'reports#expense'

  match '/email_list/index', :to => 'email_list#index'

  resources :charge_types

  resources :expenses

  resources :expense_types

  resources :expense_tax_types

  resources :clients do
    resources :support_clients
    resources :payments
    resources :charges
  end

  resources :litters
  
  resources :heat_cycles
  
  resources :dames
  
  resources :sires
  
  resources :weights do
    get 'siteHTM', :on => :collection
  end
  
  resources :puppies

  resources :colors
  
  resources :relations
  
  resources :states  
  
  resources :breeds
  
  resources :genders  
  
  resources :users

  get "available_puppies/index"
  get "available_puppies/assign_puppy"
  get "available_puppies/show"
  get "available_puppies/edit"
  post "available_puppies/update"
  
  get "sessions/new"
  
  root :to => "menu#index"
  match '/menu', :to => 'menu#index'
  match '/destroy_session', :to => 'menu#destroy_session'
  

 

end

app/models/puppy.rb
# == Schema Information
#
# Table name: puppies
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  gender_id         :integer
#  color_id          :integer
#  date_sold         :date
#  litter_id         :integer
#  collar_color_name :string(255)
#  client_id         :integer
#  notes             :text
#  created_at        :datetime
#  updated_at        :datetime
#


class Puppy < ActiveRecord::Base
  attr_accessible :name,:gender_id,:color_id,:date_sold,:litter_id,:collar_color_name,:client_id,:notes

  has_many :weights
  has_many :charges

  belongs_to :color
  belongs_to :gender
  belongs_to :litter
  belongs_to :client

  before_destroy :check_for_children

  validates :name, :presence => true
  validates :gender_id, :presence => true
  validates :color_id, :presence => true
  validates :litter_id, :presence => true

  def name_with_collar_color
    return ( name + "("+collar_color_name+")" )
  end

  def name_with_collar_color_and_litter
    return ( name + "("+collar_color_name+") - "+litter.birthday.to_s )
  end

  def newest_weight
    w_desc = weights.order(" date DESC")
    return w_desc[0] if !w_desc.nil?
    return nil
  end

  private

  def check_for_children

    if charges.count > 0
      errors[:base] << "Cannot delete puppy while a charge is assigned to the puppy."
      return false
    end
    if weights.count > 0
      errors[:base] << "Cannot delete puppy while it has weights."
      return false
    end
  end

end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  # GET /puppies
  def index
    @litters = Litter.find(:all,:order=>"birthday DESC")
    
    filter = params[:selected_litter_filter] 
    
    if filter and !filter.empty?
      @puppies = Puppy.find_all_by_litter_id(filter)
    else
      @puppies = Puppy.all
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /puppies/1
  # GET /puppies/1.xml
  def show
    #NOT USING
    @puppy = Puppy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @puppy }
    end
  end

  # GET /puppies/new
  # GET /puppies/new.xml
  def new
    @puppy = Puppy.new
    @genders = Gender.find(:all,:order=>"gender")
    @colors = Color.all
    @litters = Litter.find(:all,:order=>"birthday DESC")
    @clients = Client.all
    
    #set defalut gender to unknown
    @puppy.gender_id = Gender.where(:gender=>"Unknown")[0].id

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @puppy }
    end
  end

  # GET /puppies/1/edit
  def edit
    @puppy = Puppy.find(params[:id])
    @genders = Gender.find(:all,:order=>"gender")
    @colors = Color.all
    @litters = Litter.find(:all,:order=>"birthday DESC")
    @clients = Client.all

  end

  # POST /puppies
  # POST /puppies.xml
  def create
    @puppy = Puppy.new(params[:puppy])
    @genders = Gender.find(:all,:order=>"gender")
    @colors = Color.all
    @litters = Litter.find(:all,:order=>"birthday DESC")
    @clients = Client.all


    respond_to do |format|
      if @puppy.save
        format.html { redirect_to(puppies_path, :notice => 'Puppy was successfully created.') }
        format.xml  { render :xml => @puppy, :status => :created, :location => @puppy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @puppy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /puppies/1
  # PUT /puppies/1.xml
  def update
    @puppy = Puppy.find(params[:id])
    @genders = Gender.find(:all,:order=>"gender")
    @colors = Color.all
    @litters = Litter.find(:all,:order=>"birthday DESC")
    @clients = Client.all


    respond_to do |format|
      if @puppy.update_attributes(params[:puppy])
        format.html { redirect_to(puppies_path, :notice => 'Puppy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @puppy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /puppies/1
  # DELETE /puppies/1.xml
  def destroy
    @puppy = Puppy.find(params[:id])
    @puppy.destroy

    respond_to do |format|
      format.html { redirect_to(puppies_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/views/puppies/_form.html.erb
<%= form_for(@puppy) do |f| %>
  <% if @puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% @puppy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :litter_id %><br />
    <%= collection_select(:puppy,
                          :litter_id,
                          @litters,
                          :id,
                          :name ) %>
    <%= link_to "Add new litter", litters_path %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender_id %><br />
    <%= collection_select(:puppy,
                          :gender_id,
                          @genders,
                          :id,
                          :gender ) %>
    <%= link_to "Add new gender", genders_path %>
  </div>
  <div class="field">
    <%= f.label :color_id %><br />
    <%= collection_select(:puppy,
                          :color_id,
                          @colors,
                          :id,
                          :color ) %>
    <%= link_to "Add new color", colors_path %>
  </div>

  <div class="field">
    <%= f.label :collar_color_name %><br />
    <%= f.text_field :collar_color_name %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br />
        <%= collection_select(:puppy,
                          :client_id,
                          @clients,
                          :id,
                          :full_name,
                          :include_blank => true) %>
  </div>
 <div class="field">
    <%= f.label :date_sold %><br />
    <%= f.date_select :date_sold, :include_blank => true,
                                  :default => nil,
                                  :order => [:day, :month, :year],
                                  :use_short_month=>true %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puppies/edit.html.erb
<div class="pagenav">
  <%= link_to 'Show', @puppy %> |
<%= link_to 'Back', puppies_path %>
</div>

<h1>Editing puppy</h1>

<%= render 'form' %>

app/views/puppies/index.html.erb
<div class="pagenav">
  <%= link_to 'New Puppy', new_puppy_path %>
</div>

<h1>Listing puppies</h1>

<%= form_tag puppies_path, :method => :get do %>
    <h5>Filter by Litter  -

       <%= select_tag(:selected_litter_filter, 
                      ("<option value="">All</option>" + 
                      options_from_collection_for_select(@litters, :id, :name, params[:selected_litter_filter])).html_safe,
                      {:onchange => "this.form.submit()"} ) %>
    </h5>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Gender</th>
    <th>Color</th>
    <th>Litter</th>
    <th>Owner</th>
    <th>Date sold</th>
    <th></th>
    <th></th>
  </tr>

<% @puppies.each do |puppy| %>
  <tr>
    <td><%= link_to puppy.name_with_collar_color, puppy %></td>    
    <td><%= puppy.gender.try(:gender) %></td>
    <td><%= puppy.color.color %></td>    
    <td><%= puppy.litter.try(:name) %></td>

     <%- unless puppy.client.blank? %>
       <td><%= link_to puppy.client.try(:full_name),puppy.client %> </td>
     <%- else %>
       <td></td>
     <%- end %>

    <td><%= puppy.date_sold %></td>
    <td><%= link_to 'Edit', edit_puppy_path(puppy) %></td>
    <td><%= link_to 'Destroy', puppy, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/puppies/new.html.erb
<div class="pagenav">
  <%= link_to 'Back', puppies_path %>
</div>

<h1>New puppy</h1>

<%= render 'form' %>

app/views/puppies/show.html.erb
<div class="pagenav">
  <%= link_to 'Edit', edit_puppy_path(@puppy) %> |
  <%= link_to 'Back', puppies_path %> |
  <%= link_to 'Add Weights for Puppy', weights_path(:selected_weight_litter_filter=>@puppy.litter,
                                                    :selected_weight_puppy_filter=>@puppy) %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @puppy.name %>
</p>

<p>
  <b>Gender:</b>
  <%= @puppy.gender.try(:gender) %>
</p>

<p>
  <b>Color:</b>
  <%= @puppy.color.try(:color) %>
</p>

<p>
  <b>Date sold:</b>
  <%= @puppy.date_sold %>
</p>

<p>
  <b>Litter:</b>
  <%= @puppy.litter.try(:name) %>
</p>

<p>
  <b>Collar color name:</b>
  <%= @puppy.collar_color_name %>
</p>

<p>
  <b>Client:</b>
  <%- unless @puppy.client.blank? %>
    <%= link_to @puppy.client.try(:full_name),@puppy.client %>
  <%- end %>
</p>

<p>
  <b>Notes:</b><br>
  <%= text_area_tag :notes_text, @puppy.notes, :disabled => true %>
</p>