config/routes.rb
SummitDoodles::Application.routes.draw do
  
  resources :email_priorities
  resources :weight_reports
  
  match '/reports/expense', :to => 'reports#expense'

  match '/email_list/index', :to => 'email_list#index'

  resources :charge_types

  resources :expenses

  resources :expense_types

  resources :expense_tax_types

  resources :clients do
    resources :support_clients
    resources :payments
    resources :charges
  end

  resources :litters
  
  resources :heat_cycles
  
  resources :dames
  
  resources :sires
  
  resources :weights do
    get 'siteHTM', :on => :collection
  end
  
  resources :puppies

  resources :colors
  
  resources :relations
  
  resources :states  
  
  resources :breeds
  
  resources :genders  
  
  resources :users

  get "available_puppies/index"
  get "available_puppies/assign_puppy"
  get "available_puppies/show"
  get "available_puppies/edit"
  post "available_puppies/update"
  
  get "sessions/new"
  
  root :to => "menu#index"
  match '/menu', :to => 'menu#index'
  match '/destroy_session', :to => 'menu#destroy_session'
  

 

end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id         :integer         not null, primary key
#  date       :date
#  amount     :decimal(8, 2)
#  client_id  :integer
#  notes      :text
#  created_at :datetime
#  updated_at :datetime
#

class Payment < ActiveRecord::Base
  attr_accessible :date,:amount,:client_id,:notes

  validates :date, :presence => true
  validates :client_id, :presence => true

  validates :amount, :presence => true,
			  :numericality => true,
			  :format => { :with => /^\d{1,6}(\.\d{0,2})?$/ }

  belongs_to :client
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :load_data

  # GET /payments
  # GET /payments.xml
  def index
    @payments = @client.payments.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.xml
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.xml
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.xml
  def create
    @payment = @client.payments.build(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to(@client, :notice => 'Payment was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.xml
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to(@client, :notice => 'Payment was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.xml
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to(@client) }
    end
  end

  private

    def load_data
      @client = Client.find(params[:client_id])
    end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for([@client,@payment]) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, :order => [:day, :month, :year], :use_short_month=>true %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<div class="pagenav">
  <%= link_to 'Show', client_payment_path( @client, @payment ) %> |
  <%= link_to 'Back', @client %>
</div>

<h1>Editing payment for <%= @client.full_name %></h1>

<%= render 'form' %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Amount</th>
    <th>Client</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.date %></td>
    <td><%= number_to_currency payment.amount %></td>
    <td><%= payment.client_id %></td>
    <td><%= payment.notes %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<div class="pagenav">
  <%= link_to 'Back', @client %>
</div>

<h1>New payment for <%= @client.full_name %></h1>

<%= render 'form' %>

app/views/payments/show.html.erb
<div class="pagenav">
  <%= link_to 'Edit', edit_client_payment_path(@client, @payment) %> |
  <%= link_to 'Back', @client %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @payment.date %>
</p>

<p>
  <b>Amount:</b>
  <%= number_to_currency @payment.amount %>
</p>

<p>
  <b>Client:</b>
  <%= @payment.client.try(:full_name) %>
</p>

<p>
  <b>Notes:</b>  <br>
  <%= text_area_tag :notes_text, @payment.notes, :disabled => true %>
</p>