config/routes.rb
SummitDoodles::Application.routes.draw do
  
  resources :email_priorities
  resources :weight_reports
  
  match '/reports/expense', :to => 'reports#expense'

  match '/email_list/index', :to => 'email_list#index'

  resources :charge_types

  resources :expenses

  resources :expense_types

  resources :expense_tax_types

  resources :clients do
    resources :support_clients
    resources :payments
    resources :charges
  end

  resources :litters
  
  resources :heat_cycles
  
  resources :dames
  
  resources :sires
  
  resources :weights do
    get 'siteHTM', :on => :collection
  end
  
  resources :puppies

  resources :colors
  
  resources :relations
  
  resources :states  
  
  resources :breeds
  
  resources :genders  
  
  resources :users

  get "available_puppies/index"
  get "available_puppies/assign_puppy"
  get "available_puppies/show"
  get "available_puppies/edit"
  post "available_puppies/update"
  
  get "sessions/new"
  
  root :to => "menu#index"
  match '/menu', :to => 'menu#index'
  match '/destroy_session', :to => 'menu#destroy_session'
  

 

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # GET /expenses
  # GET /expenses.xml
  def index
    @expenses = Expense.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @expenses }
    end
  end

  # GET /expenses/1
  # GET /expenses/1.xml
  def show
    @expense = Expense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @expense }
    end
  end

  # GET /expenses/new
  # GET /expenses/new.xml
  def new
    @expense = Expense.new
    @expense_types = ExpenseType.find(:all)
    @litters = Litter.find(:all,:order=>"birthday DESC")

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @expense }
    end
  end

  # GET /expenses/1/edit
  def edit
    @expense = Expense.find(params[:id])
    @expense_types = ExpenseType.find(:all)
    @litters = Litter.find(:all,:order=>"birthday DESC")
  end

  # POST /expenses
  # POST /expenses.xml
  def create
    @expense = Expense.new(params[:expense])
    @expense_types = ExpenseType.find(:all)
    @litters = Litter.find(:all,:order=>"birthday DESC")

    respond_to do |format|
      if @expense.save
        format.html { redirect_to(@expense, :notice => 'Expense was successfully created.') }
        format.xml  { render :xml => @expense, :status => :created, :location => @expense }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @expense.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /expenses/1
  # PUT /expenses/1.xml
  def update
    @expense = Expense.find(params[:id])
    @expense_types = ExpenseType.find(:all)
    @litters = Litter.find(:all,:order=>"birthday DESC")

    respond_to do |format|
      if @expense.update_attributes(params[:expense])
        format.html { redirect_to(@expense, :notice => 'Expense was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @expense.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.xml
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to(expenses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expense_type_id %><br />
    <%= collection_select(:expense,
                          :expense_type_id,
                          @expense_types,
                          :id,
                          :name ) %>
    <%= link_to "Add new expense type", expense_types_path %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>

  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, :order => [:day, :month, :year], :use_short_month=>true %>
  </div>
  <div class="field">
    <%= f.label :litter_id %><br />
    <%= collection_select(:expense,
                      :litter_id,
                      @litters,
                      :id,
                      :birthday,
                      {:include_blank => true}) %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="pagenav">
 <%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>
</div>

<h1>Editing expense</h1>

<%= render 'form' %>

app/views/expenses/index.html.erb
<div class="pagenav">
  <%= link_to 'New Expense', new_expense_path %>
</div>

<h1>Listing expenses</h1>

<table>
  <tr>
    <th>Expense type</th>
    <th>Name</th>
    <th>Amount</th>
    <th>Date</th>
    <th>Litter</th>
    <th></th>
    <th></th>
  </tr>

<% @expenses.each do |expense| %>
  <tr>
    <td><%= link_to expense.name, expense %></td>
    <td><%= expense.expense_type.name %></td>
    <td><%= number_to_currency expense.amount %></td>
    <td><%= expense.date %></td>
    <td><%= expense.litter.try(:birthday) %></td>
    <td><%=  %></td>
    <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
    <td><%= link_to 'Destroy', expense, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/expenses/new.html.erb
<div class="pagenav">
  <%= link_to 'Back', expenses_path %>
</div>

<h1>New expense</h1>

<%= render 'form' %>

app/views/expenses/show.html.erb
<div class="pagenav">
  <%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Expense type:</b>
  <%= @expense.expense_type.name %>
</p>

<p>
  <b>Name:</b>
  <%= @expense.name %>
</p>

<p>
  <b>Amount:</b>
  <%= number_to_currency @expense.amount %>
</p>

<p>
  <b>Date:</b>
  <%= @expense.date %>
</p>

<p>
  <b>Litter:</b>
  <%= @expense.litter.try(:birthday) %>
</p>

<p>
  <b>Notes:</b>  <br>
  <%= text_area_tag :notes_text, @expense.notes, :disabled => true %>
</p>