config/routes.rb
SummitDoodles::Application.routes.draw do
  
  resources :email_priorities
  resources :weight_reports
  
  match '/reports/expense', :to => 'reports#expense'

  match '/email_list/index', :to => 'email_list#index'

  resources :charge_types

  resources :expenses

  resources :expense_types

  resources :expense_tax_types

  resources :clients do
    resources :support_clients
    resources :payments
    resources :charges
  end

  resources :litters
  
  resources :heat_cycles
  
  resources :dames
  
  resources :sires
  
  resources :weights do
    get 'siteHTM', :on => :collection
  end
  
  resources :puppies

  resources :colors
  
  resources :relations
  
  resources :states  
  
  resources :breeds
  
  resources :genders  
  
  resources :users

  get "available_puppies/index"
  get "available_puppies/assign_puppy"
  get "available_puppies/show"
  get "available_puppies/edit"
  post "available_puppies/update"
  
  get "sessions/new"
  
  root :to => "menu#index"
  match '/menu', :to => 'menu#index'
  match '/destroy_session', :to => 'menu#destroy_session'
  

 

end

app/models/charge.rb
# == Schema Information
#
# Table name: charges
#
#  id             :integer         not null, primary key
#  date           :date
#  amount         :decimal(8, 2)
#  charge_type_id :integer
#  puppy_id       :integer
#  client_id      :integer
#  notes          :text
#  created_at     :datetime
#  updated_at     :datetime
#

class Charge < ActiveRecord::Base
  attr_accessible :date, :amount, :charge_type_id, :puppy_id, :client_id, :notes

  belongs_to :client
  belongs_to :charge_type
  belongs_to :puppy

  validates :date, :presence => true
  validates :charge_type_id, :presence => true

  validates :amount, :presence => true,
			  :numericality => true,
			  :format => { :with => /^\d{1,6}(\.\d{0,2})?$/ }

end

app/models/charge_type.rb
# == Schema Information
#
# Table name: charge_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class ChargeType < ActiveRecord::Base
  attr_accessible :name

  has_many :charges

  before_destroy :check_for_children

  validates :name, :presence => true,
                   :uniqueness => { :case_sensitive => false }

  private

  def check_for_children

    if charges.count > 0
      errors[:base] << "Cannot delete charge type while a charge is using the charge type."
      return false
    end

  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  before_filter :load_data

  # GET /charges
  # GET /charges.xml
  def index
    @charges = @client.charges.find(:all)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /charges/1
  # GET /charges/1.xml
  def show
    @charge = Charge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /charges/new
  # GET /charges/new.xml
  def new
    @charge = Charge.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /charges/1/edit
  def edit
    @charge = Charge.find(params[:id])
  end

  # POST /charges
  # POST /charges.xml
  def create
    @charge = @client.charges.build(params[:charge])

    respond_to do |format|
      if @charge.save
        format.html { redirect_to(@client, :notice => 'Charge was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /charges/1
  # PUT /charges/1.xml
  def update
    @charge = Charge.find(params[:id])

    respond_to do |format|
      if @charge.update_attributes(params[:charge])
        format.html { redirect_to(@client, :notice => 'Charge was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.xml
  def destroy
    @charge = Charge.find(params[:id])
    @charge.destroy

    respond_to do |format|
      format.html { redirect_to(@client) }
    end
  end

  private

    def load_data
      @client = Client.find(params[:client_id])
      @charge_types = ChargeType.find(:all)
      @puppies = @client.puppies.find(:all)
    end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_form.html.erb
<%= form_for([@client, @charge]) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date, :order => [:day, :month, :year], :use_short_month=>true %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :charge_type_id %><br />
    <%= f.collection_select :charge_type_id,
                            @charge_types,
                            :id,
                            :name %>
    <%= link_to 'Add new charge type', charge_types_path %>
  </div>
  <div class="field">
    <%= f.label :puppy_id %><br />
    <%= f.collection_select :puppy_id,
                            @puppies,
                            :id,
                            :name_with_collar_color_and_litter,
                            :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<div class="pagenav">
    <%= link_to 'Show', client_charge_path( @client, @charge ) %> |
    <%= link_to 'Back', @client %>
</div>

<h1>Editing charge for <%= @client.full_name %></h1>

<%= render 'form' %>

app/views/charges/index.html.erb
<h1>Listing charges</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Amount</th>
    <th>Charge type</th>
    <th>Puppy</th>
    <th>Client</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @charges.each do |charge| %>
  <tr>
    <td><%= charge.date %></td>
    <td><%= number_to_currency charge.amount %></td>
    <td><%= charge.charge_type_id %></td>
    <td><%= charge.puppy_id %></td>
    <td><%= charge.client_id %></td>
    <td><%= link_to 'Show', charge %></td>
    <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
    <td><%= link_to 'Destroy', charge, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<div class="pagenav">
    <%= link_to 'Back', @client %>
</div>

<h1>New charge for <%= @client.full_name %></h1>

<%= render 'form' %>

app/views/charges/show.html.erb
<div class="pagenav">
    <%= link_to 'Edit', edit_client_charge_path(@client, @charge) %> |
    <%= link_to 'Back', @client %>
</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @charge.date %>
</p>

<p>
  <b>Amount:</b>
  <%= number_to_currency @charge.amount %>
</p>

<p>
  <b>Charge type:</b>
  <%= @charge.charge_type.try(:name) %>
</p>

<p>
  <b>Puppy:</b>
  <%= @charge.puppy.try(:name_with_collar_color_and_litter) %>
</p>

<p>
  <b>Client:</b>
  <%= @charge.client.try(:full_name) %>
</p>

<p>
  <b>Notes:</b>  <br>
  <%= text_area_tag :notes_text, @charge.notes, :disabled => true %>
</p>